services:
  master:
    build: 
      context: master
      dockerfile: ./Dockerfile
    container_name: jenkins-master
    ports:
      - "8080:8080"
    volumes:
      - ./master/.jenkins_home:/var/jenkins_home