services:
  master:
    build: 
      context: ./master
    container_name: jenkins-master
    ports:
      - "8080:8080"
    volumes:
      - ./../jenkins/master/jenkins_home:/var/jenkins_home
  
  agent001:
    container_name: jenkins-agent001
    image: jenkins/ssh-slave:latest-jdk11
    volumes:
      - ./../jenkins/agent/agent001/jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=<./../jenkins/master/jenkins_home/.ssh/agent001_id_rsa.pubの中身を貼り付けてください>